name: 'Notify Kubewarden Policy Hub'
description: 'Notify Kubewarden Policy Hub about a new policy to be added or an existing one to be updated'
branding:
  icon: 'bell'
  color: 'red'
inputs:
  USERNAME:
    description: GitHub username
    required: true
  PAT:
    description: GitHub Pesonal Access Token
    required: true
  OCITARGET:
    description: "OCI target used in the signature verification"
    required: true
runs:
  using: "composite"
  steps:
    - name: trigger policy hub update
      shell: bash
      run: |
        export TAG=$(echo $GITHUB_REF | sed -e "s|refs/tags/||")
        HTTP_CODE=$(curl \
          -s -o /dev/null \
          --user "${{ inputs.USERNAME }}:${{ inputs.PAT }}" \
          -w "%{http_code}" \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/kubewarden/policy-hub/actions/workflows/update-policy.yml/dispatches \
          -d '{"ref":"main", "inputs": {"repository": "'${GITHUB_REPOSITORY}'", "tag": "'${TAG}'", "oci-target":"${{ inputs.OCITARGET }}"}}')
        (( $HTTP_CODE == 204 ))
